.TH RADIUS-CLI "1" "June 2016" "radius-cli 0.12"
.SH NAME
radius-cli \- a remote procedure call client for Radius Core. 
.SH SYNOPSIS
radius-cli [options] <command> [params] \- Send command to Radius Core. 
.TP
radius-cli [options] help \- Asks Radius Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the radius-cli program. radius-cli is an RPC client used to send commands to Radius Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBradiusd\fP, \fBradius.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
